[package]
name = "lk-service"
description = "HTTP server, WS signal endpoints, twirp services, RoomManager, RoomAllocator, stores and agents."
edition.workspace = true
rust-version.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
