[package]
name = "lk-rtpext"
description = "RTP header extensions: dependency descriptor, abs-capture-time, playout delay, packet trailer."
edition.workspace = true
rust-version.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
