[package]
name = "lk-bwe"
description = "Bandwidth management: stream allocator, send-side BWE, remote (REMB) BWE, prober, trend detector."
edition.workspace = true
rust-version.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
